# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/notes.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/notes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/notes.proto\x12\x05notes\"&\n\x12NearbyUsersRequest\x12\x10\n\x08user_ids\x18\x01 \x03(\t\"=\n\nNearbyUser\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0c\n\x04note\x18\x03 \x01(\t\"7\n\x13NearbyUsersResponse\x12 \n\x05users\x18\x01 \x03(\x0b\x32\x11.notes.NearbyUser2W\n\x0cNotesService\x12G\n\x0eGetNearbyUsers\x12\x19.notes.NearbyUsersRequest\x1a\x1a.notes.NearbyUsersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.notes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NEARBYUSERSREQUEST']._serialized_start=28
  _globals['_NEARBYUSERSREQUEST']._serialized_end=66
  _globals['_NEARBYUSER']._serialized_start=68
  _globals['_NEARBYUSER']._serialized_end=129
  _globals['_NEARBYUSERSRESPONSE']._serialized_start=131
  _globals['_NEARBYUSERSRESPONSE']._serialized_end=186
  _globals['_NOTESSERVICE']._serialized_start=188
  _globals['_NOTESSERVICE']._serialized_end=275
# @@protoc_insertion_point(module_scope)
